### ISSUE TITLE
Research for Android app lifecycle, and background process

### ISSUE THREAD

**Issue by sahlet-official** [sahlet-official/buttonlog#24]
We need to make our app able to collect data in the background process all the time even when the UI is closed.
Consult @Yura-0 - he did this research already and knows a lot.
Reed his comments on this issue below.

- [x] To understand the difference between process and thread.
[difference-between-process-and-thread](https://www.geeksforgeeks.org/difference-between-process-and-thread/)
[difference-between-process-and-thread](https://www.guru99.com/difference-between-process-and-thread.html)
[android difference-between-process-and-thread](https://developer.android.com/guide/components/processes-and-threads (official docs))
[android process (official docs)](https://developer.android.com/reference/android/os/Process)
[android thread (official docs)](https://developer.android.com/reference/java/lang/Thread)
- [x] Find out how to divide the app into several components (app processes) so that the app can be run all the time in the background.
[app always runs in the background](https://stackoverflow.com/questions/34573109/how-to-make-an-android-app-to-always-run-in-background)
[android background (official docs)](https://developer.android.com/guide/background)
[android services (official docs)](https://developer.android.com/guide/components/services)
[android Create a background service (official docs)](https://developer.android.com/training/run-background-service/create-service)
[Running Android tasks in background threads (official docs)](https://developer.android.com/guide/background/threading)
[Youtube: How to create a background process in your Android App?](https://www.youtube.com/watch?v=tFGlLa2fwNQ&ab_channel=ProgrammerWorld)
- [x] To understand if the background app process is divided process from the UI process, or if it is the same process.
- [x] Research end understand how to solve issue #23 
- [x] Estimate size of issue #23 
(
in SP and 
![Image](https://user-images.githubusercontent.com/45210795/196357882-bb2c1dad-e388-4c27-ba6e-b23064898204.png)
)
______________

This issue size:
- Estimate SP: 5
- Actual SP: 3

**Comment by Yura-0** [comment]
1) Process means that the program is running. Opening and terminating a process takes more resources than opening and closing threads, and they are isolated from each other.
A thread is a segment of a process. Parallel streams are not isolated from each other.

**Comment by Yura-0** [comment]
2.1 Dividing the application into processes is not correct, since the application is one single process.
You can create two separate applications, one of which will be completely UI-oriented, and the second will only read the log, but due to the isolation of processes, you will have to use a buffer to store and transfer information, for example, a file. But such a solution will be the most unprofitable because it will spend much more resources to support the work of two applications.

**Comment by Yura-0** [comment]
A reasonable solution would be to create a background thread that will be responsible for reading the power key press and saving information about it to a file. This will separate the task from the main (UI) thread, and run this task in the background. But we need to choose which background thread we will run.
There are three options: immediate work, long-term work, and delayed work.
1) Immediate work includes tasks that need to be completed immediately. These are tasks that are important to the user or that you can't schedule to be deferred to a later time.
2) A job is considered long-term if it can take more than ten minutes to complete.
3) Postponed work is any work that does not need to be done immediately.
Based on the definitions, I am inclined that our task is suitable for immediate work. It does not require a lot of resources, but you need to catch the button press at the very moment it is pressed, that is, immediately.

**Comment by Yura-0** [comment]
3. When the program is opening, it is starting one process and one main thread (UI thread). To start a new background task, we need are opening a new thread and do a task on a new thread.
